# coding: utf-8

"""
    GSI Floating-Point 32 API

    **Introduction**<br> GSI Technology’s floating-point similarity search API provides an accessible gateway to running searches on GSI’s Gemini® Associative Processing Unit (APU).<br> It works in conjunction with the GSI system management solution which enables users to work with multiple APU boards simultaneously for improved performance.<br><br> **Dataset and Query Format**<br> Dataset embeddings can be in 32- or 64-bit floating point format, and any number of features, e.g. 256 or 512 (there is no upper limit).<br> Query embeddings must have the same floating-point format and number of features as used in the dataset.<br> GSI performs the search and delivers the top-k most similar results.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OrderRecordsByClusterRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'records_to_clusters_map_file_path': 'str',
        'dataset_bin_file_path': 'str',
        'centroids_file_path': 'str'
    }

    attribute_map = {
        'records_to_clusters_map_file_path': 'recordsToClustersMapFilePath',
        'dataset_bin_file_path': 'datasetBinFilePath',
        'centroids_file_path': 'centroidsFilePath'
    }

    def __init__(self, records_to_clusters_map_file_path=None, dataset_bin_file_path=None, centroids_file_path=None):  # noqa: E501
        """OrderRecordsByClusterRequest - a model defined in Swagger"""  # noqa: E501
        self._records_to_clusters_map_file_path = None
        self._dataset_bin_file_path = None
        self._centroids_file_path = None
        self.discriminator = None
        self.records_to_clusters_map_file_path = records_to_clusters_map_file_path
        self.dataset_bin_file_path = dataset_bin_file_path
        self.centroids_file_path = centroids_file_path

    @property
    def records_to_clusters_map_file_path(self):
        """Gets the records_to_clusters_map_file_path of this OrderRecordsByClusterRequest.  # noqa: E501

        Path to a file containing a map between a dataset record to its corrsponding cluster.  # noqa: E501

        :return: The records_to_clusters_map_file_path of this OrderRecordsByClusterRequest.  # noqa: E501
        :rtype: str
        """
        return self._records_to_clusters_map_file_path

    @records_to_clusters_map_file_path.setter
    def records_to_clusters_map_file_path(self, records_to_clusters_map_file_path):
        """Sets the records_to_clusters_map_file_path of this OrderRecordsByClusterRequest.

        Path to a file containing a map between a dataset record to its corrsponding cluster.  # noqa: E501

        :param records_to_clusters_map_file_path: The records_to_clusters_map_file_path of this OrderRecordsByClusterRequest.  # noqa: E501
        :type: str
        """
        if records_to_clusters_map_file_path is None:
            raise ValueError("Invalid value for `records_to_clusters_map_file_path`, must not be `None`")  # noqa: E501

        self._records_to_clusters_map_file_path = records_to_clusters_map_file_path

    @property
    def dataset_bin_file_path(self):
        """Gets the dataset_bin_file_path of this OrderRecordsByClusterRequest.  # noqa: E501

        Path to the dataset bin file path.  # noqa: E501

        :return: The dataset_bin_file_path of this OrderRecordsByClusterRequest.  # noqa: E501
        :rtype: str
        """
        return self._dataset_bin_file_path

    @dataset_bin_file_path.setter
    def dataset_bin_file_path(self, dataset_bin_file_path):
        """Sets the dataset_bin_file_path of this OrderRecordsByClusterRequest.

        Path to the dataset bin file path.  # noqa: E501

        :param dataset_bin_file_path: The dataset_bin_file_path of this OrderRecordsByClusterRequest.  # noqa: E501
        :type: str
        """
        if dataset_bin_file_path is None:
            raise ValueError("Invalid value for `dataset_bin_file_path`, must not be `None`")  # noqa: E501

        self._dataset_bin_file_path = dataset_bin_file_path

    @property
    def centroids_file_path(self):
        """Gets the centroids_file_path of this OrderRecordsByClusterRequest.  # noqa: E501

        Path to the centroids datset file.  # noqa: E501

        :return: The centroids_file_path of this OrderRecordsByClusterRequest.  # noqa: E501
        :rtype: str
        """
        return self._centroids_file_path

    @centroids_file_path.setter
    def centroids_file_path(self, centroids_file_path):
        """Sets the centroids_file_path of this OrderRecordsByClusterRequest.

        Path to the centroids datset file.  # noqa: E501

        :param centroids_file_path: The centroids_file_path of this OrderRecordsByClusterRequest.  # noqa: E501
        :type: str
        """
        if centroids_file_path is None:
            raise ValueError("Invalid value for `centroids_file_path`, must not be `None`")  # noqa: E501

        self._centroids_file_path = centroids_file_path

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrderRecordsByClusterRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrderRecordsByClusterRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
